---
# vars file for quattor-setup

quattor_gpg_key_url: http://yum.quattor.org/GPG/RPM-GPG-KEY-quattor-jrha
quattor_gpg_key_filepath: /etc/pki/rpm-gpg/RPM-GPG-KEY-quattor-jrha

quattor_repos:
  - name: quattor
    description: Quattor Repository
    baseurl: http://yum.quattor.org/{{ quattor_ver }}/el$releasever
    enabled: yes
    gpgcheck: yes
    gpgkey: file://{{ quattor_gpg_key_filepath }}
  - name: quattor_externals_arch
    description: Quattor Externals Arch
    baseurl: http://yum.quattor.org/externals/$basearch/el$releasever
    enabled: yes
    gpgcheck: no
    gpgkey: file://{{ quattor_gpg_key_filepath }}
  - name: quattor_externals_noarch
    description: Quattor Externals Noarch
    baseurl: http://yum.quattor.org/externals/noarch/el$releasever
    enabled: yes
    gpgcheck: no
    gpgkey: file://{{ quattor_gpg_key_filepath }}

quattor_rpms:
  - ant-apache-regexp 
  - ant-contrib
  - gcc
  - git
  - git-daemon
  - java-1.8.0-openjdk-devel
  - libxslt
  - libxml2
  - make
  - panc
  - knc
  - krb5-workstation
  - protobuf-compiler
  - protobuf-devel
  - python-devel
  - python-setuptools
  - aii-server

webserver_rpm : httpd

kerberos_server_rpm: krb5-server

database_rpms: 
  - sqlite

virtual_env_dep_rpms:
  - postgresql-devel
  - libxslt-devel
  - libyaml-devel
  - python-virtualenv

quattor_root_dir: /var/quattor
aquilon_venv_path: "{{ quattor_root_dir }}/aquilon-venv"

aquilon_pip_modules:
  - coverage
  - functools32
  - ipaddress
  - lxml
  - mako
  - jsonschema
  - psycopg2
  - protobuf
  - python-cdb
  - python-dateutil
  - pyyaml
  - sqlalchemy==1.3.24
  - twisted
  - virtualenv

aquilon_protocols_git_repo: https://github.com/quattor/aquilon-protocols.git
aquilon_protocols_checkout_dir: "/tmp/{{ aquilon_protocols_git_repo | basename }}"

aquilon_git_repo: https://github.com/quattor/aquilon.git
aquilon_install_dir: /opt/aquilon

  # - name: quattor_aquilon
  #   baseur: http://yum.quattor.org/aquilon
  #   enabled: 1
  #   gpgcheck: 1
  #   gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-quattor-jrha



  








